### ISSUE TITLE
Undefined report file

### ISSUE THREAD

**Issue by pavel-R5** [sumcumo/cypress-testrail-reporter#5]
Hey!
I am trying to use this reporter, but somehow it always send no results(0 passed, 0 failetd, etc.). And in log I see:
`Start Test Rail Export [ 'Automation', undefined, false, [], [] ]`

Seems like it can't see the file to read test-run results. 

The example of my config is here: 
`"testrailReporter": {
        "projectId": "1",
        "suiteId": "1",
        "host": "my.hostname",
        "user": "my@user.name",
        "password": "mypassword",
        "name": "Automation"
    },`

Any ideas what I did wrong or how to fix that?

**P.S.:** I am using [this](https://github.com/LironEr/cypress-mochawesome-reporter) reporter to get json results.

**Comment by ma-jahn** [comment]
Hi @pavel-R5 

this reporter has only been tested with the original mochawesome reporter.
Is there any chance you can switch from your `cypress-mochawesome-reporter` to this reporter https://github.com/adamgruber/mochawesome

It looks like the actual report generated by `cypress-mochawesome-reporter` has a different structure than the one created by the simple `mochawesome` reporter.

If that's not possible for you, i could have a look into the report structure and come up with am adapter interface which might allow me to offer support for multiple reporters. That would be a nice feature but also take a bit of time.

Cheers :v:

**Comment by pavel-R5** [comment]
Did that, seems like they both create similar files. May that be my mistake in configuration? 
Can you give me an example on how to set a path to json file/s for the reporter, or something like that, so I can check it?

**Comment by ma-jahn** [comment]
It should be as simple as executing
```
yarn cypress-testrail-reporter --reportFilename ./path/to/your/report.json
```
Settings like name, etc. will be extracted from your cypress.json.

**Comment by pavel-R5** [comment]
Thank you @ma-jahn  I'm using NPM but cli command looked similar, and now it appear in the log lines at least(previously I tried to add `"reportFilename": "./cypress/reports/mochawesome*.json"` to the `cypress.json` but it didn't work apparently), but it somehow thinks that there was no tests:
![image](https://user-images.githubusercontent.com/73487929/121521617-f6884780-c9fc-11eb-80d0-fd8c6f6e201f.png)

Maybe this will help:
My experimental tests look like this:
![image](https://user-images.githubusercontent.com/73487929/121522607-f50b4f00-c9fd-11eb-9410-9992a84e30e0.png)

and the report looks like this(first lines):
![image](https://user-images.githubusercontent.com/73487929/121522694-0b190f80-c9fe-11eb-9b5b-715b633f58a4.png)

What am I missing here?

**Comment by ma-jahn** [comment]
@pavel-R5 thank you for the samples. This helped me to identify the issue.
Internally i'm using a regex to strip case references from the test / suite names.
This is currently fixed and it's looking for references like "[1] name".
So in your case renaming the tests to 

"autotest loves testrail [1]"
"One more case [2]"
"autotest loves testrail [3]"

should do the trick.

I'll have a look into providing a custom regex using the `testrailReporter` options.

**Comment by pavel-R5** [comment]
Oh wow, that's unexpected :)
It worked, thank you! 

If I'm allowed to make an improvement suggestion, I'd propose next things:
1. Add the reportFilename option to use in cypress.json like:
`"testrailReporter": { ..., "reportFilename": "./your/path/to/report.json" }` .
2. Add the possibility to use API Key generated in Testrail, instead of the password, in order to provide a little more security.
3. Add the tests naming pattern explanation in README.md . Also mention there that if the case id in testrail is C1, then test name have to be like "Test [1]"(it have to be set like an array, and only number of the case is needed).
4. Add the possibility to grab and send multiple reports with similar names, using kind of a mochawesome*.json pattern.

Or maybe you have something from this list implemented already? If so, can you explain how to use it?

**Comment by ma-jahn** [comment]
Good morning @pavel-R5 

feedback is always welcome. This has been an internal package for quite a while and therefore was tailored to fit our needs. I'm happy to make amendments in order to make it easier to use.

1. Haven't thought of this approach since our reports names are like to change. But i think it would be good addition to support it for a more static setup.

2. yes yes yes :)

3. The C is only a testrail internal prefix. When working with their api the test case id is always numerical. But fair enough, i'll add a section to our Readme

4. This is actually already possible. We are using this reporter in our CI and the Cypress Jobs run in parallel. Therefore we have multiple Reports per Gitlab CI Node, like mochawesome_node1_001.json, mochawesome_node1_002.json, mochawesome_node2_001.json, and so on.
In some project we are therefore using [mochawesome-merge](https://github.com/Antontelesh/mochawesome-merge) to merge all our reports into a single big report which is than being analyzed and send to testrail.

For us it's as simple as running
```
yarn mochawesome-merge ./test/cypress/results/*.json -o ./combinedResults.json
yarn cypress-testrail-reporter --reportFilename ./combinedResults.json
```

Hopefully this setup will also work for you.
I'll add a hint to our Readme as well!

Again thank you for your feedback ✌️

**Comment by pavel-R5** [comment]
@ma-jahn Thank you for you help!
I've sorted everything up and now it is working correctly even in combination with other reporters!
